#! /bin/sh

# start sxhkd hotkey daemon
sxhkd &

# settings for multiple monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# window settings
bspc config border_width         2
bspc config window_gap          12

# split behaviour
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
