#!/bin/bash

# set keyboard layout mappings
setxkbmap dvorak
setxkbmap -option caps:escape

# set touchpad settings if xinput (and libinput) is installed
# 13 is the xinput id for the touchpad
if [ `command -v xinput` ]; then
    xinput --set-prop 13 "libinput Tapping Enabled" 1
    xinput --set-prop 13 "libinput Natural Scrolling Enabled" 1
    xinput --set-prop 13 "libinput Disable While Typing Enabled" 1
fi

# set key repeat rate
xset r rate 185 40

# start power manager
if [ `command -v xfce4-power-manager` ]; then
    xfce4-power-manager
fi

# start polybar
$HOME/dotfiles/polybar/polybar.sh

# a hack to get dunst to start correctly
systemctl --user restart dunst

# set background image
~/.fehbg &

# set screen lock hook
xss-lock -- i3lock -i $BACKGROUND_IMAGE_FILE &

# start sxhkd hotkey daemon
sxhkd &

if [ `command -v compton` ]; then
    compton --config $HOME/.config/compton/compton.conf -b
fi

# monitor settings
#bspc monitor -d I II III IV V VI VII VIII IX X
if [[ `xrandr -q | grep ' connected' | cut -d ' ' -f1 | grep HDMI2` == '' ]]; then
    bspc monitor -d I II III IV V VI VII VIII IX X
else
    bspc monitor HDMI2 -d I II III IV V VI VII VIII IX X
fi

# window settings
bspc config border_width         2
bspc config window_gap          12

# split behaviour
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# enable mouse?
bspc config click_to_focus       button1
